# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Clearives
email: clearives@gmail.com
description:
baseurl: "http://clearives.cc" # the subpath of your site, e.g. /blog
url: "http://clearives.cc" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
# baseurl: /clearives
permalink: /:title/

disqus-shortname: clearives


#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
  envs: [local]
  blanklines: false
  profile: false
  startings: []

sass:
  style: compressed

paginate: 10
paginate_path: "page:num"
# paginate_path: "/page:num"

analytics: UA-83979019-1

version: 1.0

gems: [jekyll-paginate, jekyll-seo-tag]


prose:
  rooturl: ''
  siteurl: 'http://clearives.cc'
  relativeLinks: 'https://github.com/Clearives/clearives.github.io'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
